version: '3'

services:
  mongoDB:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - ${PORT_MONGO}:${PORT_MONGO}
  api:
    container_name: api-container
    image: clean-node-api
    build: .
    restart: always
    command: npm run start:watch
    volumes:
      - ./dist/:/usr/apps/clean-node-api/dist/
      - ./package.json:/usr/apps/clean-node-api/package.json
    ports:
      - ${PORT_API}:${PORT_API}
      - 9222:9222
    links:
      - mongoDB
    depends_on:
      - mongoDB
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongoDB:${PORT_MONGO}/clean-node-api
      - PORT=${PORT_API}