version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: eslint 'src/**'
      - run:
          command: npm run test:coveralls