version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: npm install --force
      - run: npm audit fix --force
      - run: npm run lint:fix
      - run: npm run test:coveralls