version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - run: npm install
      - run: eslint 'src/**'
      - run: npm run test:coveralls