version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16
      - image: circleci/mongo:5
        environment:
          DATABASE_URL: mongodb://localhost/?
    steps:
      - checkout #alias for git clone\
      - run:
          name: Waiting for MongoDB to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MongoDB && exit 1
      - run:
          name: Install npm dependencies
          command: |
            npm install --force --save
      - run:
          name: Run unit tests
          command: |
            NODE_ENV=test && node node_modules/.bin/jest
      - run:
          name: Run e2e tests
          command: |
            NODE_ENV=test && node node_modules/.bin/jest --runInBand --config ./test/jest-e2e.json --watchAll=false --detectOpenHandles
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build_test:
    jobs:
      - run_tests
