version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: circleci/mongo:4.2.0
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install --force
      - run: sudo apt-get install -y mongodb
      - run: npm run lint:fix
      - run: npm run test:ci