version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - yarn.lock
            - ./node_modules/.cache/mongodb-memory-server/mongodb-binaries
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: yarn lint:fix
      - run: yarn test:coveralls