version: 2.1
orbs:
  node: circleci/node@4
jobs:
  build-and-test:
    executor: node/default
    steps:
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: eslint 'src/**'
      - run:
            command: npm run test:coveralls
workflows:
  build-and-test:
    jobs:
      - build-and-test