version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: circleci/node:16
    environment:
      - MONGODB_URI: ${global.__MONGO_URI__}
    steps:
      - checkout
      - run:
          name: "Print an env var stored in a Context"
          command: echo ${MONGODB_URI}
      - run: npm install --force
      - run: npm run lint:fix
      - run: npm run test:ci