version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: circleci/node:16

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: npm install --froce

      - save_cache:
          paths:
            - node_modules
            - ./node_modules/.cache/mongodb-memory-server/mongodb-binaries
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: npm run lint:fix
      - run: npm run test
      - run: npm run test:repl